### ISSUE TITLE
planes can break all block which they touch

### ISSUE THREAD

**Issue by Mareep-555** [Unknown025/Flans-Mod-Plus#106]
the "/teams "command is not work and i use the pack "warfare 44"
i really like the mod
thank you!!

**Comment by GoldSloth** [comment]
Please try setting `/teams vehiclesBreakBlocks false` and see what happens.

**Comment by Mareep-555** [comment]
it don't work , but thank you , are there any way to deal it ?

**Comment by GoldSloth** [comment]
Please provide more information than "it didn't work". What happens when you run the command?
And which version are you using?

**Comment by Mareep-555** [comment]
i use Flan's+Mod+Ultimate-1.51 , when i run the command it say "vehicles will no longer break blocks" but plane can also break blocks

**Comment by GoldSloth** [comment]
That's odd, I'll try and test it again

**Comment by Mareep-555** [comment]
thank you very much

**Comment by GoldSloth** [comment]
https://streamable.com/51zies The teams command seems to work for me.
Could you record what's happening for you, please?

**Comment by Mareep-555** [comment]
Thank you , But ,I found that it's a kind of explosion . And i use the "ForgeCreeperHeal" so it's not necessary now.Besides,I find another very very serious BUG and I solve it . Can you reply to me on discord? .I tried to tell you about the bug on discord, but you didn't answer me. my nickname is "**Mareep**"._Besides, I am Chinese, and my English is not very good.If I have any impolite words. Please forgive me for my impolite words._**I really like flan'mod and thank you for your contribution to this module**.

**Comment by GoldSloth** [comment]
I believe explosion particle effects are created, but blocks are not removed via explosion. I'm glad it's fixed for you anyway.

Regarding messaging me on Discord: I haven't received any messages from you there, I've sent you a message and a friend request so hopefully you'll be able to message me then.

Is it okay that I mark this issue as resolved?

**Comment by Mareep-555** [comment]
Okey , thank you very much
