### ISSUE TITLE
Crouching/Aiming Accuracy

### ISSUE THREAD

**Issue by Llalpaca** [Unknown025/Flans-Mod-Plus#12]
I've been enjoying the mod lately, the updates you've put out, and a lot of the options it gives me creatively. However, I do have an issue with how gun spread works when aiming/crouching. I have not been able to find any way to config it, and it appears to be a hardcoded value. Aiming seems to tighten up the spread of all weapons besides those firing multiple bullets (shotguns) significantly, and crouching seems to tighten up the spread of everything including shotguns. It doesn't make much sense for crouching to tighten the spread of shotguns, and it makes them very difficult to fit properly into the weapon sandbox. I personally think it would be better if these values were configurable on a per-gun basis, rather than the set value it is by default. Allowing further customization. This would allow for things such as very low hipfire accuracy on sniper rifles, smgs with tight hipfire spread compared to aimed spread, and just higher versatility and customization overall. If this is not possible, I would encourage you to at least take a look at the shotguns, as it really does not make sense for crouching to tighten up their spread.

**Comment by GoldSloth** [comment]
Yup, seems to be -10% for crouching and +75% spread for sprinting. I'll add it to the requested features list. Thanks for your suggestion :+1:

**Comment by GoldSloth** [comment]
Implemented in v1.40 with SprintSpreadMultiplier/SneakSpreadMultiplier in the gun. Thank you for suggesting :+1:
