### ISSUE TITLE
[BUG] Serious problem with Vehicle inventory

### ISSUE THREAD

**Issue by z5471** [Unknown025/Flans-Mod-Plus#127]
Put any two  stack of items that stack up to 33 into the vehicle inventory, then Shift click on 33 items, and the player's inventory will have two stack of 64 item.
![I 126KNLEPCG6R98CYY~Z7L](https://user-images.githubusercontent.com/50224731/162385302-128744b3-3e24-43e9-b3fc-3588a6048a0a.png)

![1 `S}YEQV(0Y2AN$9YS(P50](https://user-images.githubusercontent.com/50224731/162385306-59c054bb-57ad-46e1-9f97-e55626c74131.png)

**Comment by GoldSloth** [comment]
This may already be fixed, but not released yet.
