### ISSUE TITLE
Canceling Reload On Switching Slots

### ISSUE THREAD

**Issue by HighQualityCookie** [Unknown025/Flans-Mod-Plus#135]
I had this idea with switching slots mid reload. Usually when you switch your slot while reloading, the reload keeps going until it is finished. I was wondering if it would be possible to somehow cancel the reload when the weapon is no longer being held. Especially when you reload weapons with long reload times, it would be really helpful. Sidearms would be more useful that way.

**Comment by GoldSloth** [comment]
This has been requested before - I think Breakdown does something similar?

It'd be a nice thing to have, but requires reload times being mapped to each gun rather than the player as a whole. It's quite a big piece of work imo. I doubt I'll be able to do it, unfortunately. It'd be appreciated if someone else could, though

**Comment by pixelrider2000** [comment]
Yes, Breakdown has this feature. Sad to hear that it's so much effort. Wouldn't it be possible to get that code from Breakdown though, or doesn't that help very much?

**Comment by User4240** [comment]
> Yes, Breakdown has this feature. Sad to hear that it's so much effort. Wouldn't it be possible to get that code from Breakdown though, or doesn't that help very much?

That'd be nice though, it's pretty annoying when you accidentally reload a weapon with long reload time and you switch to other guns and can't shoot

**Comment by GoldSloth** [comment]
Thanks for your comments, we discussed it further in the Discord server and decided that there was another option:

What I was first thinking of was each weapon having its own seperate reload timer. That was the thing that was difficult to implement.

Second option is simply cancelling reload progress when slot is changed, so the reload progress is lost. That's much easier to implement, and would be in line with what you want, I think?

Does that all make sense?

**Comment by pixelrider2000** [comment]
If the end result is the same (stopping the reload), then it sounds like a pretty great solution :)

**Comment by APotatoGamerNoob** [comment]
It sounds pretty good to me

**Comment by Lightninge** [comment]
Afaik the second option is the method Breakdown uses. So yeah would be so so dope if added to Ultimate!

**Comment by GoldSloth** [comment]
@TheWillyJ is trying to add this, I believe.

**Comment by GoldSloth** [comment]
Unfortunately Willy has kind of disappeared, so it's unlikely this will get worked on for a while. Someone else might be working on it though, so I'll follow that up.

**Comment by GoldSloth** [comment]
I think `SwitchDelay` adds something like this already, i kinda forgot it existed. SecretAgent implemented it a while back.

**Comment by GoldSloth** [comment]
Closing as this is probably resolved. Please reopen if needed.
