### ISSUE TITLE
(bug) Flans Mod render problem with NEI

### ISSUE THREAD

**Issue by LavaHoleD** [Unknown025/Flans-Mod-Plus#14]
Hello, i'm having a render problem with NotEnoughItems and Flans Mod Ultimate Stability Edition.

I remember that I this error was already there when I started using Flans Mod Ultimate Stability Edition, (from 1.33) but I always forgot to report.
When one NEI page contains Flan's mod item: tile.flansWorkbench.#.name from 3 to 15, it keep it keep spamming on my console the following line:

**[Client thread/INFO]: [net.minecraft.crash.CrashReport:func_85057_a:320]: Negative index in crash report handler (0/27)**

And if I get this item the game crashes.

An user had this problem (not with flans mod ultimate stability) years ago([https://github.com/FlansMods/FlansMod/issues/822]), and explained that there's a workaround, and it's by creating a craft tweaker script, or you must use Flans Mod 4.4.0.

So I writed a script, but it gave me an error. I contacted craft tweaker devs and they told me to have the items in my hand and do /ct hand. The fact is that I cannot get those items in my hotbar without crashing.
So I can't get the registry ID.

Meanwhile (if it's fixable or not) if you know is the registry ID, can you please tell me?
I need to update my modpack and I wish to fix this error.
Have a Good day.

**Comment by GoldSloth** [comment]
Interesting, I'll try and have a look into it. Hopefully I'll be able to within the next week. Thanks for reporting it.

**Comment by LavaHoleD** [comment]
@GolddolphinSKB-Fexcraftian no problem, tell me when you solved :D

**Comment by GoldSloth** [comment]
v1.42 should fix your issues, let us know if it doesn't :+1:
