### ISSUE TITLE
Feature: when a track is destroyed, tank will not turn

### ISSUE THREAD

**Issue by User4240** [Unknown025/Flans-Mod-Plus#16]
Hello! 

First of all, great job on all the new features (and bug-fixing) you've added so far! 
But here is a very annoying problem; When a tank's track is destroyed, the tank can still turn left/right rather than remain stable and only turn its turret (this will only happen if "Tank" & "FourWheelDrive" are set to true).
I just wanted to let you know about this if you already haven't....

Thank you in advance!

**Comment by Unknown025** [comment]
Thanks for reporting this! I'll look into it.

**Comment by Unknown025** [comment]
Should be resolved in the latest commit, so will be in the next update.

**Comment by User4240** [comment]
Thank you so much!
