### ISSUE TITLE
When joining a world, (handheld) guns will initially not display animations

### ISSUE THREAD

**Issue by LavaHoleD** [Unknown025/Flans-Mod-Plus#162]
Hello, so apparently when joining a world any gun's animation will not work, neither muzzle flash. After some firing they will eventually work tho, however, it doesn't make a good impression on servers, and due to the lack of animations, initial reload will be instantaneous.

**How to reproduce**
1. Join a world
2. Reload a gun and Shoot

**Video demonstration**
https://streamable.com/bsn9xc

**Comment by GoldSloth** [comment]
Someone else has reported something similar before, we'll definitely look into this

**Comment by GoldSloth** [comment]
Appears to be fixed in the most recent build, if not: please let me know.
