### ISSUE TITLE
Flan's Mod Teams Conquest Mode

### ISSUE THREAD

**Issue by LavaHoleD** [Unknown025/Flans-Mod-Plus#163]
So there was this gamemode, Conquest, for the Teams system, which as far as I know was never finished. I just wanted to know, is resuming it planned sometime in the future?

On the official flan's mod website it says that a variable called `captureTime <time>` for Conquest mode exists, so I think base level work has been made. If it's going to be resumed, I would recommend adding the possibility of adding multiple capture points, but as for GUI reasons I would also recommend setting a limit (maybe A to F).

**Comment by GoldSloth** [comment]
I believe SecretAgent was working on it, but he's not been as active on it as of recent. You can ask him Discord if you'd like.

**Comment by LavaHoleD** [comment]
> I believe SecretAgent was working on it, but he's not been as active on it as of recent. You can ask him Discord if you'd like.

Sure thing! Could you send me a link to the discord server? `Btw, unrelated, but where is the config reference located?`

**Comment by GoldSloth** [comment]
The Discord invite's in the readme.md, so is a link to the config reference.

**Comment by GoldSloth** [comment]
![image](https://user-images.githubusercontent.com/22482566/216765078-1bfb635b-4e18-440c-8606-57d7c995f48e.png)
