### ISSUE TITLE
Game-breaking bug: Vehicle's turret does not rotate if you are looking at it from far distance

### ISSUE THREAD

**Issue by G3orge563** [Unknown025/Flans-Mod-Plus#17]
Hello,

I just wanted to let you know a really bad bug from the very first version of Flan's mod. A vehicle's turret can only be seen rotated only when someone is 50 blocks (exactly 50 blocks, I even counted it) close but when the vehicle is farther then the turret remains in it's resting position and can't be seen rotating by other players who are from a far distance but only from it's driver and players at close distance.

Thanks for reading this!

**Comment by Unknown025** [comment]
Interesting, I'll look into it. Thanks for reporting this.

**Comment by Unknown025** [comment]
Yup, you were correct. Seat updates were only being sent at exactly 50 blocks, as that was the default range for sounds. Should be fixed in the next update.

**Comment by G3orge563** [comment]
Wow man thank you so much! Hopefully I will know in the next update if my enemy is looking at me or not.

**Comment by Unknown025** [comment]
Feel free to reopen the issue if it's not fixed.
