### ISSUE TITLE
Small change in EntityBullet to prevent possible cast exceptions

### ISSUE THREAD

**Issue by AntonIT99** [Unknown025/Flans-Mod-Plus#176]
I would like to suggest a small change in _EntityBullet_. I've been working on a compatibility feature project between Flan's Mod and Custom NPCs and I ran into a casting problem in EntityBullet#**readSpawnData()**: 

At line 1538, the member **owner** is cast into _EntityPlayer_. This behavior generates an exception if the owner is actually not an _EntityPlayer_ for some reason (like in my case). Since is owner is of type _Entity_, and since there is instance checks everywhere else, casting it to _EntityLivingBase_ instead would not negatively affect anything while allowing more versatility/compatibility. This solution would be similar to the member thrower in _EntityGrenade_ which is currently cast into _EntityLivingBase_.

Suggested Fix:

replace `owner  = (EntityPlayer) obj;` by `owner  = (EntityLivingBase) obj;` on line 1538 of _EntityBullet_

**Comment by GoldSloth** [comment]
That sounds reasonable to me. Given its a small change, would it be possible for you to submit it as a pull request? Otherwise I'll add it to the Trello board and get to it at some point.

**Comment by AntonIT99** [comment]
Yes of course I can open a PR
