### ISSUE TITLE
Need help with flashbang sound

### ISSUE THREAD

**Issue by kotmatross28729** [Unknown025/Flans-Mod-Plus#178]
I'm trying to make a flashbang grenade, but the game freezes when it explodes. The logs say:

` [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'CodecJOrbis' [17:12:14] [paulscode.sound.SoundSystemLogger:errorMessage:132]:   Ogg header not recognized in method 'readHeader'. 
[paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'CodecJOrbis' [17:12:14] [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Error reading the header
`

This happens if I try to make a sound for a grenade.
If I put the sound in assets/sounds and I will indicate it name in the grenade txt itself, then there will be no sound,
I added it to sounds.json (I don't think it's right) as a 

"flashbang": {
"category" : "player",
"sounds" : [ "flansmod:flashbang" ]
},

And then the game just freezes when it explodes.
Can you tell me please how to add my own sounds?

Pack used:
[Flashbang test.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/11365850/Flashbang.test.zip)

**Comment by GoldSloth** [comment]
That suggests there's something wrong with the sound file, could you try a different sound file? It needs to be .ogg encoded. I looked in your pack and flashbang.ogg has got the right extension, but it might not be encoded properly perhaps?

**Comment by kotmatross28729** [comment]
I used a working ogg sound from another pack, renamed it and it to flashbang, and it doesn't freeze the game, however it still doesn't play

**Comment by GoldSloth** [comment]
Okay, I'll check it out tomorrow. What's the name of the grenade you're editing?

**Comment by kotmatross28729** [comment]
I took the M67 as a basis, and edited it

**Comment by GoldSloth** [comment]
https://streamable.com/lnf5yg

I've tested it out on my end with a sound that I know works (RPGShoot), and the sound plays correctly. So, not sure what's going on there.

**Comment by GoldSloth** [comment]
I'm going to close this for now, feel free to reopen it if you have more investigation into this.
