### ISSUE TITLE
Traverse sounds cannot be heard when in a dedicated server

### ISSUE THREAD

**Issue by G3orge563** [Unknown025/Flans-Mod-Plus#18]
Hello again!

I don't know if this is in the todo list but traverse sounds cannot be heard at all when in a dedicated server
Thanks

**Comment by Unknown025** [comment]
That's interesting, I haven't noticed that traverse sounds don't work on a dedicated server. I'll look into this when I can, thanks for reporting it.

**Comment by GoldSloth** [comment]
This should be fixed in the next update, I apologise that it's taken such a long time. Packets that were supposed to be carrying information about the traverse state were not.
