### ISSUE TITLE
sometimes in multiplayer position of hands of the player holding weapon reset + question

### ISSUE THREAD

**Issue by kotmatross28729** [Unknown025/Flans-Mod-Plus#180]
If 2 players are in multiplayer and one of them is holding a weapon, sometimes the position of the hands of the player holding the weapon will be reset as if he is holding some item (this does not happen with a regular bow)

https://github.com/Unknown025/Flans-Mod-Plus/assets/110309314/76264b0e-82be-4849-8277-f66084fa4d58

By the way, is it possible to disable knockback from bullets for mobs?
By default, there is a setting that disables knockback for players, but it does not affect mobs.

**Comment by GoldSloth** [comment]
Yup that looks like a bug. I'll add it to Trello and look into it at some point.

I don't think there's a way to adjust non-player knockback, though I can't remember why.

**Comment by kotmatross28729** [comment]
I noticed that in techguns, bullets have some kind of temporary "shield" to knockback, similar to damage immunity in vanilla.
That is, when a bullet hits a mob, it is knocked back 1 time and this "shield" appears, but the damage from the next bullets will be count.
In flans, absolutely all bullets that hit the mob apply knockback to it, and because of this, guns become too strong, no matter how much damage they do

https://github.com/Unknown025/Flans-Mod-Plus/assets/110309314/dce238fe-bc5f-4d44-ba28-e26efe9ce445

**Comment by GoldSloth** [comment]
I could look into adding knockback modifiers for mobs too, I can't remember exactly how it works for players but I think it could be extended.

**Comment by GoldSloth** [comment]
Tracked by https://trello.com/c/tZCEcjFV/552-add-knockback-for-mobs-too
and
https://trello.com/c/vokwV7Jx/551-multiplayer-other-players-held-item-resets-and-flickers

Closing for now, reopen or new issue if needed :)
