### ISSUE TITLE
[Questions] Attempting to make custom weapons + fixing vehicle crafting table crash

### ISSUE THREAD

**Issue by beeffeter456** [Unknown025/Flans-Mod-Plus#182]
Hello again, and thanks for taking my suggestions into account last time, its very nice to be able to suggest ideas.

Currently, I have two issues that i don't understand:

1)

I'm trying to make some custom weapons, based off of some of the guns from the Tyrants and Plebeians content packs (i know, not likely supported here because its proprietary, etc. etc.) but that not the issue, as i can convert things from those packs to work in normal Ultimate edition just fine.

The problem is that naming any box or gun that i create gives the name in-game as tile.box.name or item.gun.name or whatever instead of actually giving the weapon that name that is given in the files by the "Name" config option. I have no idea why. It works perfectly fine except for the name of the weapon, and the boxes work fine too. 

Also I'm not sure how setting weapon RPM works, does both RPM and RoundsPerMinute set the weapon rpm, or is RPM just a TaP config option?

![2023-06-22_14 41 00](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/dbd45059-143d-4acb-9440-070643a8bc56)

![2023-06-22_14 41 31](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/e9f1c32a-72b2-49dc-b32d-b898be31acdc)

2)

The vehicle crafting bench is broken, and i think I know why but I don't know how to fix it. Some items are item.null.name, and it may be contributing, but I don't know where i can modify the recipe for the ships and various vehicles added by content packs. By broken, I mean when hitting craft on any vehicle will crash the game promptly with an error such as:

[crash-2023-06-18_18.54.45-client.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11838531/crash-2023-06-18_18.54.45-client.txt)

![2023-06-22_14 44 45](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/fe1470ba-7dc2-41d7-9214-c3228c6ec858)

I also thought i have removed all duplicate vehicle entries, which can contribute to this, but maybe not? its hard to tell, so here is the log:

Edit: ok, clearly i didn't remove all duplicates, you can ignore this log 

[fml-client-latest.log](https://github.com/Unknown025/Flans-Mod-Plus/files/11839020/fml-client-latest.log)

if this isn't the right place to post this question, i'm sorry, but its the only place that can provide any help.

**Comment by GoldSloth** [comment]
Happy to help!

1. There's a file in assets/Lang or something like that, en-us is for English. There you add item.name.something=The name you want
And it should work. Check out the official packs for an example if you're not sure.

I'm not sure where item.null.name actually comes from, first time I've seen that. Could you show the config that caused that please?

**Comment by beeffeter456** [comment]
I fixed the names. Thank you!

Sure, here is the file:

[NAV_Lemnos.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11850415/NAV_Lemnos.txt)

**Comment by GoldSloth** [comment]
Thanks. I'll put on the list of things to investigate

**Comment by beeffeter456** [comment]
Hello Again,

I managed to fix the problems with the item.null, it was caused by duplicate part shortnames (again).

![2023-07-04_14 33 33](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/20f908fe-e94c-4536-a9ad-ea1af1c9c2e1)



However, pressing craft without an engine in the vehicle crafting table crashes the game for some reason. I listed the crash below. This time I made sure there was no items with the same shortname.

[crash-2023-07-04_14.14.13-client.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11951774/crash-2023-07-04_14.14.13-client.txt)

**Comment by GoldSloth** [comment]
Interesting thanks, I'll put it on the list to take a look at.

**Comment by kotmatross28729** [comment]
> Interesting thanks, I'll put it on the list to take a look at.

Wasn't that fixed in 30d4644 and 676709f ?

**Comment by GoldSloth** [comment]
First one only caused an issues when someone was playing with no vehicles in their packs. Second only applies in creative to auto-select the default engine. As in - it's likely this is a new issue.

**Comment by beeffeter456** [comment]
Hello again, hopefully I'm not bothering you with my problems too much, but I'm getting some strange behavior for some reason.

Every time I try to place a vessel from the AoW 4.4 TaP pack in the world it just crashes with a ticking entity error, apparently related to checking for collisions. I see nothing wrong with the config file compared to the original. This happens with other ships from the pack too and I have no idea why as the config looks virtually identical side by side. Other TaP ships function normally as expected. 

Crash:
[crash-2023-07-04_14.50.48-client.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11971613/crash-2023-07-04_14.50.48-client.txt)

CowPack version:
[hmswarspite.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11971621/hmswarspite.txt)

TaP version:
[T0S HMSWarspite original.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/11971623/T0S.HMSWarspite.original.txt)

**Comment by GoldSloth** [comment]
From what I'm seeing, the cow pack version has only one hitbox which is setup as core. However the TaP version uses a lot of hitboxes which don't exist in FM+USE like Turret1,turret2 e.t.c. it also doesn't set up the main part, core which iirc is required for all driveables.

I assume those only exist in TaP's version of the mod. In short, these ships aren't meant to be used on FM+USE and aren't compatible.

**Comment by beeffeter456** [comment]
Ok, so I have figured out the cause, and i guess it makes sense.

Firstly, the turret 1, 2 etc. thing is just setting up the hit boxes for the turrets themselves so they can be destroyed, commenting them out did nothing, so it wasn't that. The ship was missing a core part, so i replaced the citadel with core instead (didnt notice that originally, thanks again btw), which in addition to commenting out the buoyancy part, actually worked. This probably had something to do with the part buoyancy having some outrageously large hitbox for some reason, and I'm not sure if there is an integer limit on its size or something, or if its a special part for ships in the TAP version of the mod, but getting rid of that did the trick.

Its fortunate that the mod version they use isn't super proprietary, otherwise this conversion back to FM+USE wouldn't be possible. It does seem to have some nice features tho.

**Comment by GoldSloth** [comment]
Alright, glad it's fixed :)

**Comment by GoldSloth** [comment]
Think we fixed everything here, please reopen/new issue if not.
