### ISSUE TITLE
game crashes? when crafting a gun in a table

### ISSUE THREAD

**Issue by im-very-tired** [Unknown025/Flans-Mod-Plus#185]
when crafting a gun in a gun crafting table it causes the game to say "a fatal error has occurred, this connection is terminated" and takes me to the multiplayer screen, even though i was playing single player.

**Comment by im-very-tired** [comment]
[latest.log](https://github.com/Unknown025/Flans-Mod-Plus/files/12256142/latest.log)
heres the log file, the error can be found at the bottom

**Comment by GoldSloth** [comment]
Hm... that's quite odd. Thought it doesn't look related to flansmod. It looks like it tried to connect to the multiplayer auth servers and failed.. very weird. If it happens again in a flans related event, feel free to re-open.

**Comment by GoldSloth** [comment]
Nvm I found this still causing issues, but the error log you posted is unrelated. box.block is null on PacketBuyWeapon:47

**Comment by GoldSloth** [comment]
Seems to be caused by duplicate gun boxes with the same shortname. Please reopen if not :)
