### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by TomekHar** [Unknown025/Flans-Mod-Plus#19]
Game randomly crashes with the mod installed. Worse than with normal flans mod. Models of vehicles and guns load properly though, unlike normal flans mod. I don't know why this happens, world functions for some time and then just crashes. I have other mods installed, but they didn't interrupt normal flans mod functioning before (same other mods, no new ones installed). It happens on any version of the mod.

**Comment by Unknown025** [comment]
Mind attaching the crash report?

**Comment by TomekHar** [comment]
There is none as Minecraft displays "shutting down the internal server" message and is technically still open. This is not "out of memory" issue as my Minecraft has 8 GB of RAM to use (I have 16 in my PC, I used JVM argument in the launcher to issue more than 1 GB of RAM).

**Comment by Unknown025** [comment]
Hmm, in that case could you send the `latest.log`?

**Comment by Unknown025** [comment]
Since there's been no update to this, I'm closing the issue for the time being. Feel free to reopen if needed.
