### ISSUE TITLE
small crash with DropItemOnShoot gun config

### ISSUE THREAD

**Issue by xdeadstokex** [Unknown025/Flans-Mod-Plus#192]
DropItemOnShoot            bool
des:Drop the item when gun has been shot onto the floor

the config crash the game when gun is fired at the floor if used (either true or false)
just a fun test, the config itself is almost useless, so yeah if this is a bug, pls change the config reference to let people know not to use this config :D

**Comment by GoldSloth** [comment]
Thanks for reporting this, please could you attach the crash report you get when using this config?

**Comment by xdeadstokex** [comment]
[latest.log](https://github.com/Unknown025/Flans-Mod-Plus/files/14090549/latest.log)
here is the log
[crash-2024-01-30_05.50.05-server.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/14090554/crash-2024-01-30_05.50.05-server.txt)
and this is crash-report
(tested with no other mods)

**Comment by GoldSloth** [comment]
This was an error with the documentation, you need to provide a name for the thing you want to drop rather than a yes/no.
For instance, the panzerfaust gun in ww2 has: `DropItemOnShoot panzerfaust`.

I'll update the config accordingly, thanks for reporting it.

**Comment by xdeadstokex** [comment]
yep, I sense sth was wrong when I look at the config reference, the value is bool without telling what it drop :D
By the way, is the Shootdelay config outdated and should be replaced with roundpermin ?  and why both are capped at 1200 rpm

**Comment by GoldSloth** [comment]
Because Minecraft has 20 ticks per second, that is 20 times a bullet could be fired. That corresponds with `ShootDelay 1` and `RoundsPerMin 1200`. Any higher and you're shooting more than one bullet per tick, and you can increase damage or other techniques to compensate.

ShootDelay still works, but it doesn't let you set things that would require a decimal delay, like `RoundsPerMin 800`.

**Comment by xdeadstokex** [comment]
I should close this issue cause it is fixed :D
