### ISSUE TITLE
Game crashes when using the lwjgl3ify mod

### ISSUE THREAD

**Issue by XyDark** [Unknown025/Flans-Mod-Plus#199]
When attempting to use flans with lwjgl3ify, the game will crash with this as the reason.
![image](https://github.com/Unknown025/Flans-Mod-Plus/assets/85143697/ab381a46-7176-43da-96d5-a262cf146ca5)
![image](https://github.com/Unknown025/Flans-Mod-Plus/assets/85143697/ca383360-cce4-4c95-8edf-5e69be3b789a)

Is there any fix for this? Or is this a problem I should bring up with the lwjgl3ify dev team?

**Comment by GoldSloth** [comment]
Thanks for reporting this, are you running this in a dev environment or just in Minecraft normally?

Also, could you send a screenshot of that crash message but with more of the lines below included as well please? (The stacktrace)

**Comment by xdeadstokex** [comment]
@GoldSloth can close this thread now, may be the issuse was related to sth else or the bug "was fixed"
pic to show flan run nicely with lwjgl3ify
![image](https://github.com/user-attachments/assets/8e258333-a48c-4b83-abbf-1a283d4bfcf8)
