### ISSUE TITLE
Bug with weapons that load multiple shells?

### ISSUE THREAD

**Issue by Llalpaca** [Unknown025/Flans-Mod-Plus#2]
With a weapon that loads multiple shells, BulletInsertSound, ReloadSound, and EmptyReloadSound do not work. This leads to it being (as far as my knowledge goes) impossible to have any reload sounds for these weapons. This is likely due to the behavior being changed and either not being finished, or bugged. Either that or I'm just stupid and can't figure it out. If it is bugged, it would be nice if you could possibly add an option to go back to the old way of reloading these weapons, and fix the bug. If it's not bugged, I would like to know how to properly add sounds for these weapons.

**Comment by Unknown025** [comment]
I'll look into it. Are you sure your sounds.json file is working properly otherwise?

**Comment by Llalpaca** [comment]
Considering how I tried using the default sound and sounds that already were being used and worked with other guns (the fire sounds and reload sounds), it should be working.

**Comment by Unknown025** [comment]
Mind sharing what your weapon configuration file looks like?

**Comment by Llalpaca** [comment]
sorry, I never got sent a notification for this.
[Shotgun.R870W.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/4106447/Shotgun.R870W.txt)

**Comment by Llalpaca** [comment]
the fire sound works, and is the exact same file as bulletinsert and reload

**Comment by GoldSloth** [comment]
This should be fixed as of last update. A single bullet insert sound will play for the whole loading time, though.
