### ISSUE TITLE
FOV BUG! PLS FIX!

### ISSUE THREAD

**Issue by SecretAgent12** [Unknown025/Flans-Mod-Plus#20]
I have a FOV set to 110, but when I aim through the scope the FOV is 89, if I set the FOV to less than 89 and aim it is set to 89 !!!
Please FIX THIS !!!

I use Google translate.
Sorry for any mistakes!

**Comment by GoldSloth** [comment]
Hi SecretAgent, where are you setting this FOV?

**Comment by SecretAgent12** [comment]
In the game settings (next to the difficulty setting)

**Comment by SecretAgent12** [comment]
Can I fix this myself?

**Comment by GoldSloth** [comment]
I don't know, I haven't looked into it yet and likely won't have time to for a few weeks, sorry.

**Comment by SecretAgent12** [comment]
UP!

**Comment by GoldSloth** [comment]
I started my last set of fixes last weekend, I can try and have a look at this in the next week hopefully. You can try and fix it yourself, or investigated further if you want.

**Comment by GoldSloth** [comment]
Should be fixed in the next update.
