### ISSUE TITLE
Missing recipes in v1.57

### ISSUE THREAD

**Issue by Cronosus** [Unknown025/Flans-Mod-Plus#200]
hello
after update from 1.56 to 1.57 i have reports from players about missing recipes on my server.
some parts and fuel cannot be crafted, 

tried even in singleplayer

**Comment by GoldSloth** [comment]
Hi, we're aware of that issue and it will be fixed in the next version - for now I'd recommend downgrading to 1.56.

Update should be out in the next two months..
