### ISSUE TITLE
NTM compatibility

### ISSUE THREAD

**Issue by TheVitya2127** [Unknown025/Flans-Mod-Plus#201]
In any case, this is an improvement. As for me, the mod lacks nuclear weapons, as well as fuel from NTM.
Theoretically, adding nuclear weapons is not difficult if you use the NTM API

**Comment by GoldSloth** [comment]
What would this entail? Sorry I'm not really sure what you're suggesting.

**Comment by TheVitya2127** [comment]
I say I suggest adding nuclear weapons

**Comment by GoldSloth** [comment]
We need more info on what exactly you want to be added and why, sorry.

**Comment by TheVitya2127** [comment]
https://youtube.com/shorts/Ifw1_DWNP1E?si=x7G48N1jA7ncQ2lI

**Comment by Unknown025** [comment]
If you would like to send in a pull request with the functionality, we'd be happy to review it. That being said, both @GoldSloth and myself are focused more on maintenance rather than new features.

**Comment by TheVitya2127** [comment]
Got it, thank you
