### ISSUE TITLE
Texture corruption of uniform in version 1.59

### ISSUE THREAD

**Issue by Shaw9682** [Unknown025/Flans-Mod-Plus#203]
Well uh, I just downloaded new version of the mod and found that some uniform which put on Custom NPC and players are corrupted, and such phenomenon is not appearing in older version(1.56)
![Image_1720037498791](https://github.com/Unknown025/Flans-Mod-Plus/assets/174593752/45654929-1d8d-4075-bbf0-f472c10f4836)
![IMG_20240704_041210](https://github.com/Unknown025/Flans-Mod-Plus/assets/174593752/ea3ac908-7fa1-4ba5-bd1e-12c8409c6361)

**Comment by Unknown025** [comment]
Interesting, I haven't seen this before. Does this happen for all armor, or just certain armor? Also, does it only affect CustomNPCs or players as well?

**Comment by GoldSloth** [comment]
Possibly related to 118adc2 or 564d072.

**Comment by Shaw9682** [comment]
> Interesting, I haven't seen this before. Does this happen for all armor, or just certain armor? Also, does it only affect CustomNPCs or players as well?

It does affect on players, some of the armor are affected, but most of all are not.

**Comment by GoldSloth** [comment]
Hi, please could you try these two builds of the mod for me and see if they fix the issue?

[Builds.zip](https://github.com/user-attachments/files/16167890/Builds.zip)

**Comment by GoldSloth** [comment]
Should be fixed in the next version.
