### ISSUE TITLE
Weird shooting anim

### ISSUE THREAD

**Issue by Shaw9682** [Unknown025/Flans-Mod-Plus#204]
Just as the video shown, such phenomenon is not showing in older version.

1.56

https://github.com/Unknown025/Flans-Mod-Plus/assets/174593752/ffc3ff42-9f56-4246-8921-061680d0dcaf

1.59

https://github.com/Unknown025/Flans-Mod-Plus/assets/174593752/a62c3897-dfd0-4a35-bdf5-e232d63c7eaf

Is that the content pack's problem or what else?

**Comment by GoldSloth** [comment]
Yeah that looks like a bug, could you send me the content pack used? You can either upload it here or send it on our Discord.

**Comment by Shaw9682** [comment]
The pack is too big, I couldn't upload it, it's the link of the file.
https://www.mediafire.com/file/xd6fu6e1i8k1w8k/Warfare44ContentPack-_Version_3.2.jar

**Comment by xdeadstokex** [comment]
@GoldSloth The build 1.5902 you send me fix most if not all problem in this post.

**Comment by Shaw9682** [comment]
Yep, it solved my problem. I'll close it.
