### ISSUE TITLE
fast planes or vehicles wobble, self-destruct, eject player, flight like a maniac

### ISSUE THREAD

**Issue by xdeadstokex** [Unknown025/Flans-Mod-Plus#206]
the following pic describe a player (me) being abadoned by my dear plane and the plane act like a drunken person, it flight randomly.
This problem happen whenever the computer cannot handle chunk loading fast enough, are there anyway to mitigate this misbehavior of these vehicles beside from lower the render distance ?
![image](https://github.com/Unknown025/Flans-Mod-Plus/assets/129391255/d5bb9641-5c57-471c-a39d-6c93ebe13dcd)

**Comment by GoldSloth** [comment]
Yeah that's quite common. Trying to optimise your chunk loading or flying slower mitigates it.

We don't think there's any easy fixes we can do to improve this, sorry.
