### ISSUE TITLE
Crash on Launch with v1.59

### ISSUE THREAD

**Issue by Jackaroo05** [Unknown025/Flans-Mod-Plus#207]
Hello, upon attempting to launch the game, it crashes immediately. No other mods, no packs in the Flan folder. Link is the log file. Any help is appreciated. Thanks!

https://mclo.gs/s1xKrd0

**Comment by SecretAgent12** [comment]
![image](https://github.com/user-attachments/assets/13936262-2d36-40d0-9ceb-f1924c2af617)

**Comment by SecretAgent12** [comment]
use 1.58, wait for regular jar upload

**Comment by Jackaroo05** [comment]
Yup, that was the issue. Now I can't seem to open the part crafting table...

**Comment by GoldSloth** [comment]
The part crafting table is not functional in any Flans version - afaik it's never been implemented.

**Comment by GoldSloth** [comment]
v1.59 should now include the main release jar too. Apologies.
