### ISSUE TITLE
Vehicle Speed (Planes specifically)

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#21]
Whenever a vehicle is entered, the vehicle speed is automatically at 0.3 with no movement. With takeoff speed roughly set around 0.5, it allows for nearly instant takeoff ability no matter what i set the vehicle's physics settings to.

**Comment by GoldSloth** [comment]
Sorry, I don't quite umderstand about the default 0.3 speed thingo, the 0.5 takeoff speed is something I've noticed before, and tried to change - it's proved illusive so far. I'll add changing that to the todo list. You might be able to use drag to help with physics a bit?

**Comment by conman180** [comment]
![2021-01-31_17 34 14](https://user-images.githubusercontent.com/78190656/106400131-b2e85600-63ea-11eb-827b-93edc1d08a81.png)

Here's an example of what I was saying for clarification. I dont mind the takeoff speed being 0.5. My vehicle at rest still registes a speed of 0.3.

**Comment by GoldSloth** [comment]
Ah, I see. I'll add it to the todo list. Thanks for reporting.

**Comment by conman180** [comment]
issue was fixed when speed switched over to blocks/ sec
