### ISSUE TITLE
Flight Physics (Enhancement)

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#24]
While tinkering with the FlightController.java I figureed out how to
-Change takeoff speed of planes (nasty side effect however)
--Side Effect: At steep bank angles with the nose pointed up, plane would immediately lose its speed and lose control
-Fix to that side effect

-Change the control sensitivity at low speeds to allow for proper taxiing
The latter change however, left me with a side effect I cant seem to fix. (below)

The sensitivity change allows for all axes of control to be used at low speeds(roll, pitch, yaw).
Any ideas how to restrict the control only to yaw?

Should i attach my version of the FlightController.java below for you to look over?

**Comment by Unknown025** [comment]
So you're looking to change the controls to only regulate yaw? 

It might be helpful to view your version of FlightController.java

**Comment by conman180** [comment]
Takeoff speed is adjusted through an increase in gravity(line 37) Where I have it set makes takeoff speed at 0.72 rather than 0.5
Death stall side effect fix (lines 223 thru 226)
- Set to 40% throttle as that's the speed where landing gear no longer automatically deploy when close to the ground.
Sensitivity adjusts (lines 69 thru 72)

I'm looking to have this happen,
if speed < than a certain throttle value, then only yaw will respond, not roll or pitch.

[FlightController.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6094936/FlightController.zip)

**Comment by GoldSloth** [comment]
I've been meaning to have another go at the flight controller, mainly the lack of control at low speeds (It'd definitely be good to have yaw at those speeds) and then better control over when the plane actually takes off. I'll have a look at your code and try to do some poking this evening, to see if I can get either of these working.

**Comment by conman180** [comment]
Went through it again and figured out how to make only yaw work at low throttle settings.
(Lines 80 to 85)
also changed gravity to make the T/O speed be close to 1.0
Here is a revised FlightController.java

[FlightController.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6105452/FlightController.zip)

**Comment by GoldSloth** [comment]
I did some.. poking around. My general though is that it needs a bit of a rewrite. I'll try and do that at some point, but for now I'll try and shoehorn in y control at lower speeds.

**Comment by GoldSloth** [comment]
I've added yaw control for low speeds in the latest version, I plan to overhaul the whole flight model at some point. It's somewhat hacked together.
