### ISSUE TITLE
Explosion kills don't count in TDM

### ISSUE THREAD

**Issue by TankBill** [Unknown025/Flans-Mod-Plus#25]
Hi,

I noticed that you fixed the Flan's teams feature so I made a server with TDM and played with my friends. But while playing, we found out that explosion kills will not count as valid kills in the scoreboard of the TDM (The killer will not take any points for the kill at all) whether it is a grenade kill or from HE shells. Could this be a problem from my server or this is a bug of flan's mod?

Ι use the latest 1.44 version 

thanks

**Comment by GoldSloth** [comment]
What kind of TDM system have you got? Are you using teams or another mod/plugin?

**Comment by TankBill** [comment]
I am using the teams without any plugins/mods, just pure flan's mod

**Comment by GoldSloth** [comment]
Oke, I'll add it to the list of bugs. I probably won't get to it for quite a while, though. Teams isn't a very high priority, unfortunately.

**Comment by TankBill** [comment]
Thanks

**Comment by User4240** [comment]
Yeah I have the exact same problem, please fix it if that's possible.

**Comment by APotatoGamerNoob** [comment]
Me too

**Comment by GoldSloth** [comment]
Should be fixed in the next update.

**Comment by TankBill** [comment]
Thank you so much!
