### ISSUE TITLE
Glass Breaking Sound Plays Globally on Servers

### ISSUE THREAD

**Issue by jdawg3636** [Unknown025/Flans-Mod-Plus#26]
Running a Thermos-1.7.10-1614-57 server jar but highly doubt that's related.
Grab a minigun from the Modern Warfare Content Pack (again assuming this affects other weapons, just being as specific as possible) and shoot some glass. The high-pitched *dink* sound effect can be heard at equal volume across the entire map.

**Comment by Unknown025** [comment]
So weapon sounds are heard at equal volume to every player, regardless of distance, specifically for glass breaking?

**Comment by jdawg3636** [comment]
The sounds of the guns themselves are fine, it's just the high-pitched *dink* effect whenever a bullet hits glass that gets played globally. If you're having trouble reproducing it I can strip down my mod list a bit and try to come up with a more controlled test.
