### ISSUE TITLE
certain variables don't function

### ISSUE THREAD

**Issue by Llalpaca** [Unknown025/Flans-Mod-Plus#3]
It is worth noting that the CanHipFireWhileSprinting variable does not function. In a singleplayer world, you will be unable to hipfire while sprinting even if it is set to true, and in a dedicated server, you will always be able to hipfire while sprinting, even if it is false. Setting it does nothing. The CanShootUnderwater variable also does nothing. If you set it to false, you can still shoot underwater, in both dedicated servers and singleplayer.

**Comment by Unknown025** [comment]
That's curious, I'll have to look into this. (Sorry for the late reply, GitHub doesn't seem to send notifications for new issues being created.)

**Comment by GoldSloth** [comment]
CanHipFireWhileSprinting has been fixed (v1.39). Will use the server's value unless overriden by a gun config.

`CanShootUnderwater` was not implemented, it's on the todo list but is low priority.
Thank you for reporting :+1:
