### ISSUE TITLE
Crafted planes wont take fuel

### ISSUE THREAD

**Issue by DrunkOnSuccess** [Unknown025/Flans-Mod-Plus#31]
Crafted a plane in survival, it wont take in any fuel therefore I cannot fly it, it works if I spawn the plane in from creative mode then put fuel in though.

**Comment by GoldSloth** [comment]
Interesting, what packs are you using? And does this always happen, or just occasionally?

**Comment by DrunkOnSuccess** [comment]
Crafted three planes, Fokker DR.1, Sopwith Camel, and a BF109, no dice with any of them, recrafted the sopwith twice with a rotary and large electric engine and nada, I'm only using the base Flans mod packs and a macheteman weapon pack.

**Comment by DrunkOnSuccess** [comment]
Hey, so just did some more exploration into it, a brand-new full can of fuel wont work but if it's slightly used it works, if it has a little bit of fuel in the plane it also fuels from a brand new jerry can, so it's just a brand new plane with a brand new fuel item that won't work.

**Comment by TheoBroHax** [comment]
![Screenshot (1697)](https://user-images.githubusercontent.com/34612153/117494409-31194300-af6c-11eb-8463-a45e2634576c.png)

**Comment by DrunkOnSuccess** [comment]
![Screenshot (1699)](https://user-images.githubusercontent.com/34612153/117494472-47bf9a00-af6c-11eb-8bef-c6f5330b3e76.png)

**Comment by Unknown025** [comment]
That's...interesting. Did this just start with the last release, or is it also broken in the last update?

Thanks for looking into this by the way.

**Comment by DrunkOnSuccess** [comment]
Broken in the last one and latest. If you'd like I could go back through versions and try and see the earliest it breaks?

**Comment by Unknown025** [comment]
It's fine, but thanks. Was just wondering if it was a recent bug or not. I'll look into it when I get the chance.

**Comment by Unknown025** [comment]
Sorry it's taken a while. I haven't been able to replicate this. Either this was fixed recently, or it's a more complicated problem. Is it still a problem in the most recent releases?

**Comment by GoldSloth** [comment]
I doubt it's fixed, sadly. I believe the same bug occurred a lot on the server, and seemed to be fairly random. But once the plane was borked, it wouldn't work at all, no matter what you did with it - which suggests an issue stuck in the NBT. I've got the NBT of a broken vehicle in the trello, but I haven't found much difference with a working one, sadly.

**Comment by Unknown025** [comment]
Ah, I see. Since crafting a vehicle in creative or survival seems to be the same, but broken NBT data would make sense. Does breaking the vehicle and replacing it fix the problem, or is that saved NBT data persistent?

**Comment by GoldSloth** [comment]
Breaking replacing doesn't seem to fix it, which I think means the NBT isn't corrupted, but the issue is with a value in DriveableData that is set. I can point you towards the NBT of an item where this occurred, assuming this is the same bug, it's very rare and therefore a pain to reproduce.

**Comment by GoldSloth** [comment]
The NBT for my player, taken from world/playerdata is here: 
https://trello.com/c/fqImNtIQ/182-planes-being-unable-to-fuel 

I think it should be fairly easy to work out which item is the Flans one.

**Comment by conman180** [comment]
I've found that the engine you use determines if the crafted vehicle will take fuel. if you craft using the same engine that is in the tooltip for the creative menu, it will accept fuel. If you use any other engine however, it wont.

**Comment by Unknown025** [comment]
@conman180 If that's the case, sounds like a different bug. I don't remember if Flan's will allow you to craft a vehicle with an incompatible engine.

**Comment by Unknown025** [comment]
Since there haven't been any mentions of this reoccurring since, I'm going to assume this is fixed or at least mitigated. If not, feel free to reopen.
