### ISSUE TITLE
Killing vehicles with..... knives!

### ISSUE THREAD

**Issue by APotatoGamerNoob** [Unknown025/Flans-Mod-Plus#32]
Hello, I recently played in a LAN world with my friends, and I was in a vehicle with 100% HP and one came with a knife and "stabbed" my vehicle numerous times and I died (the vehicle blew up)! 

Is there a way to stop things that use melee to damage vehicles? They can also destroy a vehicle with vanilla items that use melee damage!

**Comment by GoldSloth** [comment]
Melee hits will damage the vehicle, aye. It'll probably be a lot of hits though - a normal melee hit is like, 5 damage maybe? And a lot of Flans vehicles will have health in the region of 100 to even 1000s.

It'd be possible to add a multiplier in the mod config to change how effective melee is, possibly?

**Comment by APotatoGamerNoob** [comment]
Oh ok, because the content pack I am using has melee damage 18 to its knives and vehicles have health from 100 to 200.

**Comment by GoldSloth** [comment]
Aye, the difference there is a lot smaller. Would you want me to implement that modifier, then?

**Comment by APotatoGamerNoob** [comment]
Yes if possible, that would help a tanker blow up others without having to worry for them if they get close and get stabbed. Also game mechanics would change too I believe, so players in general will use anti-tank stuff rather than stabbing them with simply knives....

**Comment by GoldSloth** [comment]
I've added the config `MeleeDamageDriveableModifier` to the gun type, you should  be able to specify this for each of your guns and control it's effectiveness against vehicles. Warning: I haven't tested this, at all. I really wanted to get this release out, so any testing you can do would be very appreciated :)

**Comment by GoldSloth** [comment]
Going to close this as it has been resolved.
