### ISSUE TITLE
Passenger guns issue

### ISSUE THREAD

**Issue by User4240** [Unknown025/Flans-Mod-Plus#33]
Hi, 

When I put an ammo stack (2 magazines for an example) to a passenger's gun, it will only use the one instead but it will consume both of them! If one mag has 50 bullets and I put x2 mags in, it will only fire 50 but it will consume the other mag too while it should fire 100! 

This happens in any case, no matter how many magazines you've added in the passenger's gun ammo slot.
Except if this is a driver's gun, then it works just fine.
It also existed in other versions too.

**Comment by GoldSloth** [comment]
Thanks for reporting, I'll take a look into it the next time I'm working on Flans.

And sorry it's taken a while to reply, I've been pretty busy. Hope it hasn't caused too much issues for you.

**Comment by GoldSloth** [comment]
I can confirm I've been able to replicate this, I'll work on a fix now.

**Comment by GoldSloth** [comment]
Should be fixed by 46e42de5c56a9c83794fed643811a178aa0695f3, will be in next update. Thanks for reporting ;)
