### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Nitric-acid-CN** [Unknown025/Flans-Mod-Plus#34]
Could you add some option in Config that can ban enchanting the armor of Flan's Mod Plus?
It could always bring some problem.

**Comment by GoldSloth** [comment]
Hi, I'm glad to say that this feature already exists in the flansmod.cfg mod configuration file. If you set armour enchantability to  0, it can't be enchanted with tables or anvils. Hope that helps 🙂

**Comment by Nitric-acid-CN** [comment]
> Hi, I'm glad to say that this feature already exists in the flansmod.cfg mod configuration file. If you set armour enchantability to 0, it can't be enchanted with tables or anvils. Hope that helps 🙂

Now I know it, Thank you!
