### ISSUE TITLE
Flashlight Bug

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#36]
The only time the flashlight attachment function seems to work is when it is a grip attachment. If I say, make it a gadget attachment, the light does not work.

**Comment by GoldSloth** [comment]
Interesting, I'll look into it. It sounds like this is the behaviour that was designed though, so adding the flashlight ability to other types of attachments would prob be a feature.

**Comment by GoldSloth** [comment]
Okay, I've implemented this now, thanks for the suggestion.
