### ISSUE TITLE
Have i just to drag and drop this mod?

### ISSUE THREAD

**Issue by Stormez1998** [Unknown025/Flans-Mod-Plus#37]
The question is very Simple and idk if im to stupid or to tired but have i to replace ur Version with the original or have i to took both mods into the mods folder?

Thanks!

**Comment by Stormez1998** [comment]
Edit: i have found out to replace it. but then i do the whole game crashes. Makes no difrenc if i try to join my local host server or a singleplayer world

**Comment by GoldSloth** [comment]
Hi there, you need to remove the original version of Flansmod to use this version, and put it in your mods folder. If you're crashing, can you send us the crash report please? They're in the crash-reports folder.

**Comment by Unknown025** [comment]
@Stormez1998 is this still an issue? Otherwise, I'm going to close this.

**Comment by Stormez1998** [comment]
I have to tryed it out bcs i was demotivated but my question was answerd :) thanks. But i will try it out

**Comment by Unknown025** [comment]
Glad to hear. Feel free to reopen this if you need to.
