### ISSUE TITLE
Hot to add muzzle flashes to custom models?

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#40]
I'm currently working on a custom content pack but I can't seem to get muzzle flashes working. So I was wondering if you can actually add them to your gun and if so, how? Because I'm pretty sure you can, since I saw them working on other guns when playing this flans mod version. And secondly where can I ask questions about the mod? I feel like that this is not the right place ;)

I hope you can help me on that, much thanks!

**Comment by pixelrider2000** [comment]
Don't you hate it when you resolve the issue 20 minutes after you ask... I would still like to know where to ask such questions though :)

**Comment by GoldSloth** [comment]
Is this all sorted now? You can ask questions like this here, or on Discord, if you have it. I'll put a link to our Discord in the readme on the front page :)

**Comment by pixelrider2000** [comment]
Yeah I've fixed the problem! But it's still good that I know where to ask questions now ;)

**Comment by GoldSloth** [comment]
np, glad to hear you got it sorted out.
