### ISSUE TITLE
Burst weapons automatically firing after reload

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#41]
When you left click (try to shoot with) an empty burst gun and then reload (with R), a burst goes off even though the player didn't make any new inputs after that inital left click when it was still unloaded. 

Hope this hasn't been mentioned yet ;)

**Comment by GoldSloth** [comment]
Interesting, will add to the todo list. Thanks for reporting.

**Comment by GoldSloth** [comment]
Hm, for me it seems to only occur after right clicking, pressing R doesn't have an effect - the code suggests that too. Shall investigate further.

**Comment by GoldSloth** [comment]
Probable cause found, both server and client keep track of how many bullets left in a 'burst'. Client counts down each tick regardless of if a bullet was found, and the server will only tick down once it's shot something - so it'll eternally be trying to shoot.

**Comment by GoldSloth** [comment]
Okay, I believe I've fixed it. Would you mind testing this build to confirm?

[Archive.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6766401/Archive.zip)

**Comment by pixelrider2000** [comment]
The gun doesn't seem to unwillingly fire anymore after the reload, so it appears to be fixed. Though I've spotted another bug regarding burst guns but I'm sure it's pretty much the same as the last. Basically, once again when you reload the empty gun via left/right click the animations (muzzle flash/bullet ejection) still fire.

Here is  a link to a video I recorded that shows exactly what I mean: https://www.mediafire.com/file/6mo530nme45vvjj/Animation+bug.mp4/file

**Comment by GoldSloth** [comment]
Many thanks for testing, I'll try and fix this next issue ;)

**Comment by GoldSloth** [comment]
I think I've fixed it, would you mind testing it again, please?

[Test.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6794243/Test.zip)

**Comment by pixelrider2000** [comment]
The bug is indeed fixed! But for some reason the previous bug, where the weapon fires unwillingly occured again. Did you just send me an older version or did this bug really sneak in again? ;)

**Comment by GoldSloth** [comment]
Strange, I haven't been able to reproduce that on my client.. Possible that I sent you a half-built version, I'll send another one now.
Just to make sure, to reproduce:
- Empty gun, no ammo left in inventory
- Right click/reload
- Pickup ammo
- Issue occurs when gun shoots off rounds
[eeeee.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6795101/eeeee.zip)

**Comment by pixelrider2000** [comment]
I think I understand now. It's true that when you left/right click, pick up the ammo and then reload, there is no trouble. The gun only goes off when you spam click your fire button while picking up the ammo (and then reload). So I suppose it's a matter of whether or not you click while you pick up the ammo. I'm of course not sure if that is correct but that makes sence to me :)

**Comment by GoldSloth** [comment]
Ah, I see. It's not exactly what's wanted, but I can't see it as particularly annoying. Would you like it if it changed, and didn't "queue" up shots while you're reloading?

**Comment by pixelrider2000** [comment]
I was thinking the same, it's probably not that big of a deal! Honestly, I think it depends on how much you value this issue yourself and also if you have the time to deal with such petty problems ;) Maybe you could keep it in the back of your head and just fix it when there is time.

**Comment by GoldSloth** [comment]
Alright, thank you for your consideration :)) I'll add it to the list, but the priority is somewhat lower than other issues. Is it alright if we close this issue, now? Many thanks for reporting the issue and testing.
