### ISSUE TITLE
Hitmarkers not working properly!

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#43]
When playing with friends, we noticed that hitmarkers were not working properly. Basically when shooting at players/entities (when they are moving) the hitmarker goes off without the entity taking damage or the hitmarker doesn't go off but the entity is taking damage. My theory is that when you shoot straight at a moving entity the hitmarker shows up because the entity was in your line of sight but the bullet is still traveling thus not necessarily damaging the entity. This bug makes hitmarkers very misleading and we unfortunately had to turn them off on our multiplayer server.

Because this bug is kind of weird to explain I recorded a video: https://www.mediafire.com/file/9wt2qttno6tru7f/Hitmarker_shenanigans.mp4/file

Keep up the good work!

**Comment by GoldSloth** [comment]
Good morning, this bug is known about and unfortunately it's due to hits that register on the client but not the server, I will link my explanation so you can read it if you want. https://github.com/FlansMods/FlansMod/issues/1390

It's on my to-do list, but it's a very large chunk of work and I'm not sure when I'll be up to dive into it again.

So, sorry I'm not able provide a fix currently. Hopefully sometime in the future, though!

**Comment by pixelrider2000** [comment]
I see, that's very unfortunate. I wish you the best of luck fixing it anyways :)
But just out of curiosity, couldn't a hit system work something like that; When a player takes damage due to a bullet (and the server registers that damage), it's being checked who shot the bullet and this person gets the hitmarker. Please keep in mind that I'm looking at this issue from a bukkit/spigot developer perspective, I have very little experience with forge ;) It's probably not that easy though since your explanation of the system seemed to factor in a lot more variables. I'd love to (try to) help as much as possible anyways because a reliable hitmarker system would just be awesome. Please let me know if I can help in any shape or form with this issue, thanks!

**Comment by GoldSloth** [comment]
That would be a solution, but it could take a significant time for the hit marker result to come back, the player's ping + processing time + 20ms for the tick, I think the latency would cause issues in other ways, could be confusing if you're shooting in full auto especially. I've been thinking about it a bit today as well, and I think I've got some ideas to make it a bit more accurate,.(as in, more hits correctly registered on the server), which has a good change of fixing some of these client issues I think. I'll let you know of progress on that.

If that doesn't work, then I'll have a look at implementing what you suggested, that's a good backup plan.

**Comment by GoldSloth** [comment]
Is it alright if I close this for now? When further development happens on the issue, it'll be in the release notes.
