### ISSUE TITLE
Toggle weapon model disappearance on scoped weapon

### ISSUE THREAD

**Issue by HighQualityCookie** [Unknown025/Flans-Mod-Plus#44]
When I tried to put a simple crosshair as scope (pictures attached), I noticed that the weapon model disappears. And then I thought it would be pretty cool if you could toggle the weapon model disappearence. That would make toggleable crosshairs pretty easy to implement like that. Let me know if that could be a thing or if something like this even already exists (or can be achieved in another way). 

Much thanks!

![2021-07-12_01 39 04](https://user-images.githubusercontent.com/87285346/125213280-0a4ff380-e2b2-11eb-857d-4095f692a40e.png)
![2021-07-12_01 39 07](https://user-images.githubusercontent.com/87285346/125213286-15a31f00-e2b2-11eb-98ab-66f483bea680.png)

**Comment by GoldSloth** [comment]
Heya, thanks for using the mod, I believe the feature you're looking for exists already, and is implemented in quite a few packs. Like the ACOG from the MW pack?
https://github.com/Unknown025/Flans-Mod-Plus/blob/Ultimate/eclipse/Flan/Modern%20Weapons%20Pack/attachments/ACOGSight.txt

You can see comments in here too, explaining what the different variables do.
`//These variables only come into effect if this is a scope
//The ZoomLevel affects how much the view zooms in (note that this removes the model from the zooming animation and so is useless for iron sights)
//The FOVZoomLevel affects how much the view narrows when zooming. Very useful for iron sights as it gives the illusion of zooming without killing off the model
ZoomLevel 1.0
FOVZoomLevel 2.0
ZoomOverlay None`

I think you need to use FOVZoomLevel, and make sure ZoomLevel is 1.
Hope that helps, let me know if you have anymore questions :)

**Comment by HighQualityCookie** [comment]
The problem was not that I don't know how to zoom in but how to keep the model of the gun as well as the red crosshair (that you can see in the second picture) at the same time.

EDIT: I'm not using an attachment btw.

**Comment by GoldSloth** [comment]
Ah, okay. Wasn't sure before. Can you send the config of the gun? I can have a look and see what options are available there.

**Comment by HighQualityCookie** [comment]
Here it is.
[FirstPistol.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/6804847/FirstPistol.txt)

**Comment by GoldSloth** [comment]
I'm not sure there is a way currently, the way a lot of scopes work is to have one built into the model, with a high res texture semi-transparent in it, in the model as well. To display a 2d texture as well, I'll have to investigate further when I have time.

Are you wanting this only when the player scopes/ADS/aims, not constantly?

**Comment by HighQualityCookie** [comment]
I only want the crosshair to be shown when the player ADS. I'm also aware of the fact that most current iron sights are build into the model itself. But I would really love to see this feature, so you can just put a GUI over the screen much like a sniper scope; but simply without the model disappearing.

**Comment by GoldSloth** [comment]
Oke, I'll hopefully get to investigate this fairly soon - and probably get this into the next release if it's not there already.
Thank you for your questions and feedback ;)

**Comment by HighQualityCookie** [comment]
On the same note, I had another idea. May you also implement an option where you can disable the zooming animation altogether? So when you ADS/zoom in, the weapon just doesn't move at all. Appreciated ;)

**Comment by GoldSloth** [comment]
Interesting. Out of curiosity, what's the attraction of this effect? I assume you want to combine the overlayed ADS texture with the zero movement?

**Comment by HighQualityCookie** [comment]
That's pretty much the case. The gun that I'd love to capture just has some unique features; and to achieve a greater level of detail on that gun, these options would just be amazing!

**Comment by GoldSloth** [comment]
https://streamable.com/mtghhy
Some progress. Got the gun to display or not when scoped via a config option. Looks like it was just being moved behind the eyes before. It doesn't work with ZoomLevel currently, so I'll have to investigate that. Then, looking at the animations for moving to and from ADS. My hope is to make those configurable, so you can choose exactly where it moves to - but the code there is.. cryptic. I'll link it here if you're interested.

https://github.com/Unknown025/Flans-Mod-Plus/blob/Ultimate/src/main/java/com/flansmod/client/model/RenderGun.java#L175
175-218 pretty much.

**Comment by HighQualityCookie** [comment]
Looks pretty good so far 👍

**Comment by GoldSloth** [comment]
I should add, do you mind much about zooming?

**Comment by HighQualityCookie** [comment]
Yes, it´s quite important to me.

**Comment by GoldSloth** [comment]
I'm completely surprised by this, but it looks like the reason this isn't possible is down to forge/minecraft, not Flansmod..

As we can see in this screenshot:
![image](https://user-images.githubusercontent.com/22482566/126848783-e25154f8-9817-4882-b108-cc0596ace527.png)

If the cameraZoom isn't 1, it just.. doesn't render. I had to install intellij to try and track this down, and I'm quite frustrated at this.
I'm sure it is possible to do, but I lack the skills to do it, I'm afraid. My apologies that this will probably be quite disappointing news for you..

Based on that, the only option then is to use the FOV change, just without any magnification.

Next step is to make the animation settings for ADS configurable.

**Comment by HighQualityCookie** [comment]
I think a zoom via FOV-change would also be pretty good. I can't wait to get my hands on these features ;) I really appreciate the effort, no need to apologize. Thanks a lot!

**Comment by GoldSloth** [comment]
Heya, I had a go at enabling control over all animation settings for ADS, but there's too much going on to simplify into variables.
For now, I've just added two, you need to put these in your model file.

```Java
// Render gun even when scope overlay is displayed
stillRenderGunWhenScopedOverlay = true;
// Effects the amount of movement to do when ADS. 1 = normal 0 = none e.t.c.
adsEffectMultiplier = 0;
```

A demo can be seen here:
https://streamable.com/g5j9jw

I've included a build with the feature in, would be grateful if you could provide feedback on it. Let me know if you have anymore questions :)
[rel.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6873157/rel.zip)
Disclaimer: This build may have bugs in it, and is not a proper release. Only suitable for testing atm.

**Comment by HighQualityCookie** [comment]
Thanks for the build. But can I just write this in the config file or do I need to put it somewhere else?

**Comment by HighQualityCookie** [comment]
Thanks for the build! I´ll try it out.

**Comment by HighQualityCookie** [comment]
Works just the way I wanted it to. Thanks alot!

**Comment by GoldSloth** [comment]
Great! Glad that's what you wanted. It'll be released fully in the next version. Can this issue be closed now?

**Comment by HighQualityCookie** [comment]
Yep
