### ISSUE TITLE
Vehicles falling too fast

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#47]
I noticed that vehicles were falling too fast to the ground. In my experience it felt more like teleporting, rather than an actual descend. I would thus suggest decreasing the speed at which the vehicle falls.

**Comment by GoldSloth** [comment]
Hello again, I'll do some testing and see if I can make it a bit smoother. A config option for the speed also feels like a good idea.

I'd ideally like to make a system that doesn't allow the "gliding" that I personally despise, but not instant teleport down. I'll take some videos and post them here to see what you think. Thanks for the feedback ;)

**Comment by pixelrider2000** [comment]
That sounds like a great idea! But one thing, you mentioned gliding and I personally think it'd be great if there is an option in the config (e.g. on/off/glide-distance) or something like that). Because I think that it would be a shame if vehicles couldn't make any sort of jumps anymore.

**Comment by pixelrider2000** [comment]
Thinking more about it... maybe you could implement some kind of new system that determines the kind of jump depending on all sorts of values. For example the angle at which you leave the ground (so when the vehicle is angled upward, you actually ascend) or the speed which then determines the distance etc. I reckon that be a lot of work but I wanted to mention it anyways ;)

**Comment by GoldSloth** [comment]
Some of them perhaps. Things like exit angle are already factored in by the physics model, though. All of them would be a bit over the top, imo.

**Comment by pixelrider2000** [comment]
Perhaps you're right... too many might be a bit far fetched. In the end you gotta decide for yourself though ;)

**Comment by GoldSloth** [comment]
Apologies for the delay, this issue was on low priority for quite a while.

I've had a poke around with it today, it's proving very difficult because the wheel system is very janky. I'll see what I can do. My first goal is a generic 'max fall speed', then an accelerating factor, then we'll see after that.

**Comment by pixelrider2000** [comment]
That sounds pretty good to me, good luck on that!

**Comment by pixelrider2000** [comment]
It appears that this issue has been resolved in the newest version right? May I close this now?

**Comment by GoldSloth** [comment]
Yep, o introduced the two parameters for control of falling.
Apologies I did not come back and update this issue
