### ISSUE TITLE
Game Crash when i playce a Tank or Plane

### ISSUE THREAD

**Issue by Stormez1998** [Unknown025/Flans-Mod-Plus#49]
Its Me again :D 

I tryed out like i sayed and the game works so damn good. I intalled then later Contentpacks and tested out again. I play on my own server. So yeah i tryed to place tank, SERVER CRASHED, i restartet take another one, SERVER CRASHED. i will aply my lates log of the Server hopefully someone can help me :) Thanks. BTW im on Ubuntu 10. Server Version 1.7.10

[latest.log](https://github.com/Unknown025/Flans-Mod-Plus/files/6904260/latest.log)

**Comment by GoldSloth** [comment]
Can you post the crash report, please? It's located in /home/Thermos/./crash-reports/crash-2021-07-29_23.58.56-server.txt

**Comment by GoldSloth** [comment]
Going to close this due to lack of response.
