### ISSUE TITLE
Minor Propeller Bug (not game breaking)

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#50]
I've noticed that when a pilot exits any plane while moving, after a few seconds, the propellers disappear. Helicopters seem to be unaffected. However, when you break the plane and replace it, the propeller is there again. The only time the prop wont disappear is if you exit after you've come to a complete stop.
![2021-08-01_23 44 30](https://user-images.githubusercontent.com/78190656/127801714-abf41c3c-476c-4fb7-baf4-9fd895c15265.png)

Just found it kind of odd.

**Comment by GoldSloth** [comment]
~~Thats our new feature!~~ That's very strange lel, I would guess the position goes to null or NaN somehow. I'll look into it.

**Comment by GoldSloth** [comment]
Fixed in 5bd0def07da9312528b4f4e3b9482b807264d80d
