### ISSUE TITLE
Vehicles getting stuck on slopes

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#52]
I don't know if this is a known issue because this problem inevitably occures when driving over rough terrain with vehicles in the newest 1.47 release (it doesn't seem to happen in older releases).
It's pretty straight forward, when driving over some rough terrain (mostly when driving downhill), there is a pretty high chance the vehicle will get stuck. And the chances of breaking free are very slim. 

I hope this issue can be fixed since it makes the newest release practically unplayable which is very unfortunate.

Here is a video that shows the problem: https://www.mediafire.com/file/pa04t3m3rcwnoao/VehiclesStuck.mp4/file

Thanks!

**Comment by GoldSloth** [comment]
This should be fixed in the version which is yet to be released, it's caused by seat collisions. You can disable those in flansmod.cfg for the time being. Let me know if that works ;)

**Comment by pixelrider2000** [comment]
Disabling seat collision does indeed fix the problem. And since you already fixed the bug, this issue seems to be resolved now. But I would like to know when I can expect the next version to be released.

**Comment by GoldSloth** [comment]
I'm planning for it to be done by the very latest, a month's time.
I'm 3/4 way through a promised feature which is taking a very long time, and I'd like to get a couple more in before releasing.
Sorry for the delay, my time availability has been a bit odd recently.

**Comment by pixelrider2000** [comment]
Thanks for letting me know. I'll close this issue then ;)
