### ISSUE TITLE
Knifes not working in F5

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#53]
Melee weapons such as the "knife" from the modern weapons pack won't damage any enemies in F5 (third person). You can neither hit mobs nor players. It's not that severe but I wanted to mention it anyways.

**Comment by GoldSloth** [comment]
Okay, it looks like next release will be melee related! Had lots of other bug reports relating to it. Thanks for reporting.

**Comment by GoldSloth** [comment]
Hallo, sorry for the delay. Had a quick look, the melee functionality works, but it's only the animations that don't work. Therefore this can probably be a feature request instead of a bug. You just need to keep your camera as though you were in first person.

The difficulty is, offsets and animation stuff needs to be written separately for third person.
How important would this be to you?

**Comment by pixelrider2000** [comment]
I'm actually not talking about those melee weapons that have a model and an animation but rather about "normal looking items". I don't know if the same applies for those but if so, I still can't get a single hit on an entity no matter how much I try. But regardless of whether I am just too retarded to hit the enemy or it's actually a bug, I don't think it's that of an important feature/bug. But I would definitely love to see melee animations working in third person since you mentioned it :) (also low priority though) 

Here is a video showing what I mean: https://www.mediafire.com/file/gkokr9k2n7xzp86/F5Bug.mp4/file

**Comment by GoldSloth** [comment]
Ahhh, I see. I'm not entirely sure how those work, so I'll have to have a look.

**Comment by GoldSloth** [comment]
I've had a quick look, I can't really determine how to go about enabling this in third person - the simple melee mode just assigns a damage value using the vanilla melee system. I'm not sure it's really worth much time so I'm probably going to add it low down on the feature request list, if that's okay. Please let me know if you've got anything further on it :)
