### ISSUE TITLE
SetPlayerInvisible Bug

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#61]
Player remains invisible when vehicle being ridden is destroyed. Forces a world reload to become visible again.

**Comment by GoldSloth** [comment]
Does this happen with planes, and vehicles too?

**Comment by conman180** [comment]
All Driveables. Correction from earlier: getting into another driveable and exiting makes the player visible.

**Comment by GoldSloth** [comment]
Interesting, I remember making numerous changes to this before, so something's gone wrong at some point lel. Thanks for reporting, I'll put it on the list

**Comment by GoldSloth** [comment]
https://streamable.com/5s67gw Fixed, issue was that non-creatives were killed on vehicle death, so creatives would not be set invis because only the vehicle died: the seat dismount thingo did not.
Fixed by 3b5efe3fa00beefe3eda75176266d26ed40a99eb, thanks for reporting :)
