### ISSUE TITLE
Spectator mode idea

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#66]
I think that there should be a way to make bullets go through players **without changing the penetration of the bullet**. This would be especially useful for a spectator mode, since the spectator would not be able to block bullets anymore. My idea was a command like "/spectator [PLAYERNAME] true/false" or something similar. Simply changing the penetration would not have the same effect since a bullet with penetration would also go through multiple entities for example, not only players.

**Comment by GoldSloth** [comment]
This seems like more of a teams idea, I'll add it to the list. @Unknown025 is this something you could consider with the other teams shenanigans?

**Comment by Unknown025** [comment]
Sure, I'll look into it. I'm not sure how useful this would be, considering the player would still visible to everyone else on a server, since 1.7.10 doesn't have a native spectator mode.

**Comment by GoldSloth** [comment]
I feel like there may be mods or plugins that allow fake players that wouldn't get hit anyway, not sure it's completely in the scope of the mod.
Not sure how teams spectator mode works? If that is just flying around, then maybe we should consider it to hook into that.

**Comment by pixelrider2000** [comment]
When I thought of spectator mode I really just envisioned this basic command rather than actually deeply implementing a spectator mode into flans very own game modes. Because when creating your own game modes with flans mod, it currently isn't possible to have a "good" spectator mode. I can set the player invisible, I can make him fly, but unfortunately I can't make bullets go through the player. This is why I thought a simple command like that would be very helpful. Even when you're just messing around and someone wants to spectate the others, he can just punch in the command and doesn't have to worry about blocking any bullets. These were my ideas and visions at least :)

**Comment by GoldSloth** [comment]
Aye, I understand that - some thought needs to be given to how it fits in with the teams spectator mode that already exists in the mod, and what the best way to use it would be.

**Comment by GoldSloth** [comment]
Closing for now, this requires a more cohesive plan I think?
