### ISSUE TITLE
Gun Pump

### ISSUE THREAD

**Issue by BrayLopez24** [Unknown025/Flans-Mod-Plus#67]
Gun pump instantly slides like a slide, and then do its normal pump animation. Looks bad on snipers and shotguns.
PD: Is in my AWM sniper

https://user-images.githubusercontent.com/91297394/134603422-eddc4b4d-c198-4dca-8c6e-3cfcafeff461.mp4

**Comment by GoldSloth** [comment]
I believe this was fixed in a fairly early version, is the issue resolved for you?

**Comment by BrayLopez24** [comment]
It already fixed, i had release 1.1, now, i have the release 1.4. My
friends and I loves the headshots in multiplayer :)

**Comment by GoldSloth** [comment]
No problem, glad it's resolved.
