### ISSUE TITLE
[Suggestion] Second Skin Layer removal upon wearing a 3D armor

### ISSUE THREAD

**Issue by LavaHoleD** [Unknown025/Flans-Mod-Plus#71]
In Minecraft 1.8, second layer skin was supported for any body part and it was made in settings that you could toggle them. However, in 1.7, only Hat layer was supported which couldn't been toggled. This (especially when playing with your friends, where you notice it more) would cause to users with a hat layer wearing a 3D flans mod helmet glitching the second skin layer with the helmet. It's something that in years we always had, but what if it was fixed? As far as I know, it's not really hard to implement. Call to battle 2 did that too. Could this feature be added? 

Edit: actually, this could be added when wearing any armor part. Because many pack authors make for example helmets and such in just all one part, which usually isn't the helmet.

**Comment by SecretAgent12** [comment]
@GoldSloth @Unknown025 
Hello

I suggest adding hideSecondSkinLayer to the armor parameters.

**Comment by GoldSloth** [comment]
Sure, it's a good idea.

But - actually hiding the second skin layer may not be easy at all. We'll have to see.

**Comment by LavaHoleD** [comment]
Alright, good luck!

**Comment by GoldSloth** [comment]
Tracked by https://trello.com/c/FFxbZb5Z/361-second-skin-layer-hiding-for-armour
Please reopen or make a new ticket if needed.
