### ISSUE TITLE
Reload time multiplier for attachments doesnt work as intended

### ISSUE THREAD

**Issue by AveriAeterna** [Unknown025/Flans-Mod-Plus#8]
The gun will play a recoil animation as if it was firing while simultaneously playing the reload animation at the original speed. The gun will still not fire anything until the reload animation is done playing.

![2020-08-05_19 26 17](https://user-images.githubusercontent.com/10492088/89473800-cd01ee00-d751-11ea-93d8-4674900a7415.png)

I used a gun with muzzle flashes to help visualize the bug better, but the bug is still present on other guns I have tested with my attachment.

![bug](https://user-images.githubusercontent.com/10492088/89473962-4699dc00-d752-11ea-9502-97f2b35800be.PNG)
This is the attachment I am using on the guns. I made the multiplier small so I could better test what was going on.

**Comment by GoldSloth** [comment]
Thank you for your report, I'll add it to the trello board. Hopefully it should be fixed in the next few weeks.

**Comment by GoldSloth** [comment]
Fixed in commit 306d7bb. Release in the next few day on curseforge.
