### ISSUE TITLE
Muzzle flash visible on every gun

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#83]
I'm currently fiddling around with the newest version of the mod. First I wanna say that the hitmarkers seem to work pretty well now. I've done some testing with a friend and we didn't get even one false positive/negative, I was really glad to see that :)

But I noticed that every weapon has a muzzle flash now (only visible by other players). Is there a way to turn this off, since it often doesn't quite match the position of the barrel? And if it is, do I have to do it for every gun individually or is there a way to turn it off in general? It is a great feature but I think you should have to turn it on if you want it on your gun, rather than having to turn it off for a lot of guns where the flash doesn't quite align with the barrel.

Thank you

**Comment by GoldSloth** [comment]
Hallo, glad to see you're enjoying the new update.

You can modify for each gun the following configs related to muzzle flash particles:
![Screenshot_20211104-091037-604](https://user-images.githubusercontent.com/22482566/140287618-3bd98a37-9925-4c66-9307-ddade7cd3b02.png)

The reason that they're on by default in first person, is that even though the default position isn't going to line up for some guns, imo it's good enough for regular players to have that benefit without having to fiddle with packs.

It would be possible to add a config in flansmod.cfg which would set a default, which could be overridden in the individual gun config, would you like that?

**Comment by pixelrider2000** [comment]
I understand. I think a config option for either "showing" or "hiding" muzzle flashes on default would still be pretty nice though.

**Comment by BrayLopez24** [comment]
I was also going to comment on that, anyway,  it can help me too. Silencer do a good job :)

https://user-images.githubusercontent.com/91297394/141819132-8ecf4131-0224-4016-8e50-5cc8a3479efc.mp4

**Comment by GoldSloth** [comment]
Added in d4c55e46cac14b7d930d5f156ad8915a2d7e18f3, which will be in the next release.
