### ISSUE TITLE
committing suicide with a sledge hammer

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#88]
When you use the sledge hammer while walking (forward) you can hit yourself with it. I've tested this with a couple of other melee weapons, that work in a similar way but I've only had this bug on the sledge hammer.

Here is a video showing the bug: https://streamable.com/tzr64j

**Comment by GoldSloth** [comment]
Alright, I'll reopen this card on trello.

**Comment by GoldSloth** [comment]
Fixed by fb75dcdbc7f776c47c86515aec568898707a2b4c :)
