### ISSUE TITLE
Flan's team mod is broken and compiling is broken too

### ISSUE THREAD

**Issue by User4240** [Unknown025/Flans-Mod-Plus#9]
Hello,

Recently I had been playing with friends this version of flansmod and we tried to set up a map to play on Team Death Match and CTF. After we made the team files and classes in the W44 pack, we added the commands that's needed to start the match.

The game started normally (/teams start) but after the match ended it just got stuck and didn't start a new match.

Another issue I'm facing is that when I created the workspace to add new models and code them, when I finished them I typed in the Windows Powershell ./gradlew.bat build and got this error: 

C:\Users\panze\Desktop\Flansmod Workspace\build\sources\java\com\flansmod\common\FlansMod.java:137: error: diamond operator is not supported in -source 1.6
    public static ArrayList<BlockGunBox> gunBoxBlocks = new ArrayList<>();
                                                                      ^
  (use -source 7 or higher to enable diamond operator)
1 error
1 warning
:compileJava FAILED

I don't know if I'm stupid or blind (or both) but I still can't figure out how to fix that and I need help.
Thanks

**Comment by Unknown025** [comment]
Hey there,

This means that you are either using an older Java JDK version, or didn't enable the right source properties. An easy way to check that is `java -version`. Depending on your Java IDE, it might have settings related to this.

**Comment by User4240** [comment]
Oh thanks you just saved my small content pack.

**Comment by Unknown025** [comment]
Glad you could figure it out.
